apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app
spec:
  replicas: 10
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: bendeez/rafka-test-as-client:app
        imagePullPolicy: Always  
        ports:
        - containerPort: 3000
        env:  
        - name: BROKER_URL
          value: "http://rafka-service:8000"
