apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker-deployment
  labels:
    app: broker 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker 
  template:
    metadata:
      labels:
        app: broker 
    spec:
      containers:
      - name: broker 
        image: bendeez/rafka-test-as-client:broker
        ports:
        - containerPort: 8000  

  
