apiVersion: apps/v1
kind: Deployment
metadata:
  name: rafka-deployment
  labels:
    app: rafka 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rafka 
  template:
    metadata:
      labels:
        app: rafka 
    spec:
      containers:
      - name: rafka 
        image: bendeez/rafka-test-as-client:broker
        imagePullPolicy: Always
        ports:
        - containerPort: 8000  

  
